name: Track TODOs

on:
  push:
    branches:
      - main

jobs:
  # Usage: https://github.com/marketplace/actions/todo-to-issue#usage
  track-todos:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5.1.14
        with:
          CLOSE_ISSUES: true
          AUTO_ASSIGN: true
          LANGUAGES: .github/workflows/todo-tracking/syntax.json
