name: Track TODOs

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      MANUAL_COMMIT_REF:
        description: "The SHA of the commit to get the diff for"
        required: true
      MANUAL_BASE_REF:
        description: "By default, the commit entered above is compared to the one directly before it; to go back further, enter an earlier SHA here"
        required: false

jobs:
  # Usage: https://github.com/marketplace/actions/todo-to-issue#usage
  track-todos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5.1.14
        env:
          MANUAL_COMMIT_REF: ${{ inputs.MANUAL_COMMIT_REF }}
          MANUAL_BASE_REF: ${{ inputs.MANUAL_BASE_REF }}
        with:
          CLOSE_ISSUES: true
          AUTO_ASSIGN: true
          LANGUAGES: .github/workflows/syntax.json
          INSERT_ISSUE_URLS: true

      - name: Set Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and create PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add -A
          if [[ $(git status --porcelain) ]]; then
            BRANCH_NAME="todo-issue-links-$(date +%s)"
            git checkout -b "$BRANCH_NAME"
            git commit -m "docs(todos): add issue links"
            git push origin "$BRANCH_NAME"
            gh pr create --fill --head "$BRANCH_NAME"
            gh pr merge "$BRANCH_NAME" --squash --delete-branch --admin
          else
            echo "No changes to commit"
          fi
